---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- name: images
  type: image_gallery
  config: {}
  label: images
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
- type: text
  name: discount_price
  label: discount_price
- name: macka_ali_pes
  type: select
  default: Mačka
  config:
    required: true
    options:
    - Mačka
    - Pes
    source:
      type: simple
      section: 
      file: 
      path: 
  label: mačka ali pes
pages:
- exampleSite/content/english/macke/crno-bel-muc-tablica.md
- exampleSite/content/english/macke/tigrasta-macka.md
- exampleSite/content/english/psi/bigl-tablica.md
