---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: file
  name: image
  label: image
- name: images
  type: image_gallery
  config: {}
  label: images
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
- type: text
  name: discount_price
  label: discount_price
- type: list
  name: sizes
  label: sizes
- name: kategorija
  type: tag_list
  default: []
  label: Kategorija
  description: kategorija izdelka
  hidden: false
